### ISSUE TITLE
Command Line Interface Request

### ISSUE THREAD

**Issue by reflexdemon** [char0n/http-request-in-editor#248]
**Is your feature request related to a problem? Please describe.**
I like this tool a lot. We need to be able to run it as cli. I am unable to find any documentation for running it on terminal. I see a lot of potential for that.
**Describe the solution you'd like**
It would be nice if we can have the tool be able to be installed as global CLI so that we could run it on terminals. For example, `http-request http-request-file.http`. This will make the tool more widely adopted.

**Describe alternatives you've considered**
At present other than using VS Code or Jet Brain's IDEs there is no CLI options.

**Additional context**
See [this description](https://youtrack.jetbrains.com/issue/IDEA-239345#focus=Comments-27-2860462.0-0) for what I am actually looking for

**Comment by char0n** [comment]
@reflexdemon I'll have it in my TODO to describe where we are with the implementation of progress of this library.

Have a loot at: https://youtrack.jetbrains.com/issue/IDEA-239345. There is mention of two runners, one I think is written in GO. I currently work on runner that will use already implemented parser in this repo. Keep an eye on this repo, more is comming shortly.

**Comment by char0n** [comment]
Initial support for runtime: https://github.com/char0n/http-request-in-editor/pull/250

CLI interface on top of this will come shortly.
