### ISSUE TITLE
request target bug

### ISSUE THREAD

**Issue by jupegarnica** [char0n/http-request-in-editor#334]
**Describe the bug**
the children of request-target node is an array of arrays. is it  the expect beheavior?

```js
{
  type: "request-target",
  location: 5,
  children: [ [ { type: "absolute-form", location: 5, children: [Array] } ] ]
}

```
**To Reproduce**

```js
import { parse } from 'https://cdn.skypack.dev/http-request-in-editor';

const http = `
GET http://example.com

###
`;
const cst = parse(http);
```

**Expected behavior**
I expect: 
```js
{
  type: "request-target",
  location: 5,
  children: [ { type: "absolute-form", location: 5, children: [Array] } ] 
}

```

**Screenshots**

![image](https://user-images.githubusercontent.com/3143445/154992593-a31ec08a-2d58-4944-affa-3aef010f2d1e.png)

**Comment by char0n** [comment]
This looks like a bug...inspecting.

**Comment by char0n** [comment]
Fixed in https://www.npmjs.com/package/http-request-in-editor/v/0.4.0

**Comment by jupegarnica** [comment]
nice xD
